<a href="https://colab.research.google.com/github/armansayed41-ship-it/Road-to-ML-Engineer/blob/main/pandas_day_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import pandas as pd
df = pd.read_csv("/content/sales_analysis.csv")

In [73]:
df["Total_Sales"] = df["Price"] * df["Quantity"]
print(df)

   Order_ID Customer  Age  Gender       City     Category     Product  Price  \
0      O001    Rahul   22    Male    Kolkata  Electronics      Laptop  55000
1      O002    Priya   25  Female      Delhi  Electronics  Headphones   2500
2      O003     Aman   29    Male     Mumbai      Fashion       Shoes   3200
3      O004    Sneha   21  Female    Kolkata      Fashion     T-Shirt    800
4      O005    Arjun   31    Male  Bangalore  Electronics  Smartphone  28000
5      O006     Neha   24  Female      Delhi      Fashion       Jeans   1800
6      O007    Rohit   27    Male     Mumbai  Accessories       Watch   4500
7      O008     Isha   23  Female    Kolkata  Electronics    Keyboard   2200
8      O009    Vikas   35    Male    Chennai  Accessories    Backpack   1500
9      O010    Pooja   28  Female  Bangalore      Fashion       Dress   2500
10     O011      Dev   26    Male      Delhi  Electronics       Mouse   1200
11     O012     Riya   30  Female     Mumbai  Accessories  Sunglasses   1800
12     O013    Karan   33    Male    Kolkata  Electronics     Monitor  14000
13     O014    Tanya   22  Female    Chennai      Fashion     T-Shirt    900
14     O015   Manish   38    Male  Bangalore      Fashion       Shoes   3500
15     O016   Simran   27  Female      Delhi  Electronics  Smartwatch   6500
16     O017   Aditya   24    Male     Mumbai  Accessories      Wallet   1000
17     O018    Meera   29  Female    Kolkata  Electronics      Tablet  22000
18     O019    Sahil   32    Male    Chennai      Fashion       Jeans   1900
19     O020   Anjali   26  Female  Bangalore  Electronics  Headphones   2800
20     O021    Varun   23    Male    Kolkata  Electronics       Mouse   1300
21     O022    Kavya   25  Female      Delhi      Fashion       Jeans   2000
22     O023    Harsh   28    Male     Mumbai  Accessories       Watch   5000
23     O024    Nisha   24  Female  Bangalore  Electronics      Tablet  21000
24     O025     Yash   30    Male    Chennai      Fashion       Shoes   3600

    Quantity Payment  Order_Date  Total_Sales
0          1     UPI  2026-01-05        55000
1          2    Card  2026-01-07         5000
2          1     UPI  2026-01-10         3200
3          3    Cash  2026-01-12         2400
4          1    Card  2026-01-15        28000
5          2     UPI  2026-01-18         3600
6          1    Card  2026-01-20         4500
7          1     UPI  2026-01-22         2200
8          2    Cash  2026-01-25         3000
9          1    Card  2026-01-28         2500
10         3     UPI  2026-02-02         3600
11         2    Card  2026-02-05         3600
12         1     UPI  2026-02-08        14000
13         2    Cash  2026-02-10         1800
14         1    Card  2026-02-13         3500
15         1     UPI  2026-02-16         6500
16         2    Cash  2026-02-18         2000
17         1    Card  2026-02-21        22000
18         2     UPI  2026-02-24         3800
19         1    Card  2026-02-27         2800
20         2     UPI  2026-03-01         2600
21         1    Card  2026-03-03         2000
22         1    Cash  2026-03-05         5000
23         1     UPI  2026-03-07        21000
24         2    Card  2026-03-10         7200

In [74]:
total_order = df["Order_ID"].count()

In [75]:
total_quantity = df["Quantity"].sum()

In [76]:
df["Order_ID"].count()

np.int64(25)

In [77]:
df["Total_Sales"].mean()

np.float64(8432.0)

In [78]:
df["Price"].mean()

np.float64(7620.0)

In [79]:
df.groupby("City")["Total_Sales"].sum()

City
Bangalore    57800
Chennai      15800
Delhi        20700
Kolkata      98200
Mumbai       18300
Name: Total_Sales, dtype: int64

In [80]:
df.groupby("Category")["Total_Sales"].sum()

Category
Accessories     18100
Electronics    162700
Fashion         30000
Name: Total_Sales, dtype: int64

In [81]:
df.groupby("Category")["Total_Sales"].mean()

Category
Accessories     3620.000000
Electronics    14790.909091
Fashion         3333.333333
Name: Total_Sales, dtype: float64

In [82]:
df.groupby("Product")["Quantity"].sum()

Product
Backpack      2
Dress         1
Headphones    3
Jeans         5
Keyboard      1
Laptop        1
Monitor       1
Mouse         5
Shoes         4
Smartphone    1
Smartwatch    1
Sunglasses    2
T-Shirt       5
Tablet        2
Wallet        2
Watch         2
Name: Quantity, dtype: int64

In [83]:
df.loc[df["Price"].idxmax(),"Product"]

'Laptop'

In [84]:
df.loc[df["Total_Sales"].idxmax()]

Order_ID              O001
Customer             Rahul
Age                     22
Gender                Male
City               Kolkata
Category       Electronics
Product             Laptop
Price                55000
Quantity                 1
Payment                UPI
Order_Date      2026-01-05
Total_Sales          55000
Name: 0, dtype: object

In [85]:
df.loc[df["Total_Sales"].idxmax(), "City"]

'Kolkata'

In [86]:
df.loc[df["Total_Sales"].idxmax(), "Category"]

'Electronics'

In [87]:
df.groupby("Customer")["Total_Sales"].sum().sort_values(ascending=False).head(5)

Customer
Rahul    55000
Arjun    28000
Meera    22000
Nisha    21000
Karan    14000
Name: Total_Sales, dtype: int64

In [88]:
(df.groupby("Payment")["Total_Sales"].sum() / df["Total_Sales"].sum()) * 100

Payment
Card    38.472486
Cash     6.736243
UPI     54.791271
Name: Total_Sales, dtype: float64

In [89]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [90]:
df["Order_Date"].dt.year

0     2026
1     2026
2     2026
3     2026
4     2026
5     2026
6     2026
7     2026
8     2026
9     2026
10    2026
11    2026
12    2026
13    2026
14    2026
15    2026
16    2026
17    2026
18    2026
19    2026
20    2026
21    2026
22    2026
23    2026
24    2026
Name: Order_Date, dtype: int32

In [91]:
df["Month"] = df["Order_Date"].dt.month

In [92]:
df["Order_Date"].dt.day

0      5
1      7
2     10
3     12
4     15
5     18
6     20
7     22
8     25
9     28
10     2
11     5
12     8
13    10
14    13
15    16
16    18
17    21
18    24
19    27
20     1
21     3
22     5
23     7
24    10
Name: Order_Date, dtype: int32

In [93]:
df.groupby("Month")["Total_Sales"].sum()

Month
1    109400
2     63600
3     37800
Name: Total_Sales, dtype: int64

In [94]:
df.groupby("Month")["Order_ID"].count()

Month
1    10
2    10
3     5
Name: Order_ID, dtype: int64

In [95]:
df.groupby("Product")["Total_Sales"].sum().sort_values(ascending=False).head(3)

Product
Laptop        55000
Tablet        43000
Smartphone    28000
Name: Total_Sales, dtype: int64

In [96]:
df.groupby("City")["Total_Sales"].mean().idxmax()

'Kolkata'

In [97]:
df.groupby("Category")["Quantity"].sum().idxmax()

'Electronics'

In [98]:
df.groupby("Customer")["Quantity"].sum().sort_values(ascending=False).head(3)

Customer
Dev       3
Sneha     3
Aditya    2
Name: Quantity, dtype: int64

In [99]:
best_product = df.groupby("Product")["Quantity"].sum().idxmax()

In [101]:
print("Total Orders = ", total_order)
print("Total Quantity = ", total_quantity)
print("Total Sales = ", df["Total_Sales"].sum())
print("Average Order Value = ", df["Total_Sales"].mean())
print("Highest Order Value = ",df["Total_Sales"].max())
print("Best selling product = ", best_product)

Total Orders =  25
Total Quantity =  38
Total Sales =  210800
Average Order Value =  8432.0
Highest Order Value =  55000
Best selling product =  Jeans