<a href="https://colab.research.google.com/github/armansayed41-ship-it/Road-to-ML-Engineer/blob/main/pandas_day_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [173]:
import pandas as pd
df = pd.read_csv("/content/customer_orders.csv")
city_df = pd.read_csv("/content/city_details.csv")
order_df = pd.read_csv("/content/new_orders.csv")
df.shape

(21, 11)

In [174]:
df.columns

Index(['Order_ID', 'Customer', 'Age', 'Gender', 'City', 'Product', 'Category',
       'Price', 'Quantity', 'Payment_Method', 'Order_Date'],
      dtype='object')

In [175]:
df.dtypes

Order_ID           object
Customer           object
Age               float64
Gender             object
City               object
Product            object
Category           object
Price             float64
Quantity            int64
Payment_Method     object
Order_Date         object
dtype: object

In [176]:
df.isnull().sum()

Order_ID          0
Customer          0
Age               2
Gender            0
City              0
Product           0
Category          0
Price             1
Quantity          0
Payment_Method    0
Order_Date        1
dtype: int64

In [177]:
df.drop(columns =["Payment_Method"])

,Order_ID,Customer,Age,Gender,City,Product,Category,Price,Quantity,Order_Date
0,O001,Rahul,22.0,M,Kolkata,Laptop,Electronics,55000.0,1,2026-01-05
1,O002,Priya,25.0,F,Delhi,Headphones,Electronics,2500.0,2,2026-01-07
2,O003,Aman,NaN,Male,Mumbai,Shoes,Fashion,3200.0,1,2026-01-10
3,O004,Sneha,21.0,Female,Kolkata,T-Shirt,Fashion,800.0,3,2026-01-12
4,O005,Arjun,27.0,M,Bangalore,Smartphone,Electronics,28000.0,1,2026-01-15
5,O006,Neha,24.0,F,Delhi,Jeans,Fashion,NaN,2,2026-01-18
6,O007,Rohit,27.0,male,Mumbai,Watch,Accessories,4500.0,1,2026-01-20
7,O008,Isha,23.0,F,Kolkata,Keyboard,Electronics,2200.0,1,NaN
8,O009,Vikas,35.0,Male,Chennai,Backpack,Accessories,1500.0,2,2026-01-25
9,O010,Pooja,28.0,F,Bangalore,Dress,Fashion,2500.0,1,2026-01-28
10,O011,Dev,NaN,M,Delhi,Mouse,Electronics,1200.0,3,2026-02-02
11,O012,Riya,30.0,Female,Mumbai,Sunglasses,Accessories,1800.0,2,2026-02-05
12,O013,Karan,33.0,M,Kolkata,Monitor,Electronics,14000.0,1,2026-02-08
13,O014,Tanya,22.0,F,Chennai,T-Shirt,Fashion,900.0,2,2026-02-10
14,O015,Manish,38.0,Male,Bangalore,Shoes,Fashion,3500.0,1,2026-02-13
15,O016,Simran,27.0,F,Delhi,Smartwatch,Electronics,6500.0,1,2026-02-16
16,O017,Aditya,24.0,M,Mumbai,Wallet,Accessories,1000.0,2,2026-02-18
17,O018,Meera,29.0,Female,Kolkata,Tablet,Electronics,22000.0,1,2026-02-21
18,O019,Sahil,32.0,M,Chennai,Jeans,Fashion,1900.0,2,2026-02-24
19,O020,Anjali,26.0,F,Bangalore,Headphones,Electronics,2800.0,1,2026-02-27
20,O005,Arjun,27.0,M,Bangalore,Smartphone,Electronics,28000.0,1,2026-01-15

In [178]:
df_copy = df.copy()
df_copy = df_copy.dropna()

In [179]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [216]:
df["Price"] = df["Price"].fillna(df["Price"].mean())

In [181]:
df["Order_Date"] = df["Order_Date"].fillna("Unknown")

In [182]:
df["Gender"] =df["Gender"].replace("M","Male")
df["Gender"] =df["Gender"].replace("male","Male")
df["Gender"] =df["Gender"].replace("F","Female")

In [183]:
df.rename(columns={"Customer": "Customer_Name", "Price": "Unit_Price", "Quantity": "Qty", "Order_Date": "Date"})

,Order_ID,Customer_Name,Age,Gender,City,Product,Category,Unit_Price,Qty,Payment_Method,Date
0,O001,Rahul,22.000000,Male,Kolkata,Laptop,Electronics,55000.000000,1,UPI,2026-01-05
1,O002,Priya,25.000000,Female,Delhi,Headphones,Electronics,2500.000000,2,Card,2026-01-07
2,O003,Aman,27.368421,Male,Mumbai,Shoes,Fashion,3200.000000,1,UPI,2026-01-10
3,O004,Sneha,21.000000,Female,Kolkata,T-Shirt,Fashion,800.000000,3,Cash,2026-01-12
4,O005,Arjun,27.000000,Male,Bangalore,Smartphone,Electronics,28000.000000,1,Card,2026-01-15
5,O006,Neha,24.000000,Female,Delhi,Jeans,Fashion,27.368421,2,UPI,2026-01-18
6,O007,Rohit,27.000000,Male,Mumbai,Watch,Accessories,4500.000000,1,Card,2026-01-20
7,O008,Isha,23.000000,Female,Kolkata,Keyboard,Electronics,2200.000000,1,UPI,Unknown
8,O009,Vikas,35.000000,Male,Chennai,Backpack,Accessories,1500.000000,2,Cash,2026-01-25
9,O010,Pooja,28.000000,Female,Bangalore,Dress,Fashion,2500.000000,1,Card,2026-01-28
10,O011,Dev,27.368421,Male,Delhi,Mouse,Electronics,1200.000000,3,UPI,2026-02-02
11,O012,Riya,30.000000,Female,Mumbai,Sunglasses,Accessories,1800.000000,2,Card,2026-02-05
12,O013,Karan,33.000000,Male,Kolkata,Monitor,Electronics,14000.000000,1,UPI,2026-02-08
13,O014,Tanya,22.000000,Female,Chennai,T-Shirt,Fashion,900.000000,2,Cash,2026-02-10
14,O015,Manish,38.000000,Male,Bangalore,Shoes,Fashion,3500.000000,1,Card,2026-02-13
15,O016,Simran,27.000000,Female,Delhi,Smartwatch,Electronics,6500.000000,1,UPI,2026-02-16
16,O017,Aditya,24.000000,Male,Mumbai,Wallet,Accessories,1000.000000,2,Cash,2026-02-18
17,O018,Meera,29.000000,Female,Kolkata,Tablet,Electronics,22000.000000,1,Card,2026-02-21
18,O019,Sahil,32.000000,Male,Chennai,Jeans,Fashion,1900.000000,2,UPI,2026-02-24
19,O020,Anjali,26.000000,Female,Bangalore,Headphones,Electronics,2800.000000,1,Card,2026-02-27
20,O005,Arjun,27.000000,Male,Bangalore,Smartphone,Electronics,28000.000000,1,Card,2026-01-15

In [184]:
df["City"].unique()

array(['Kolkata', 'Delhi', 'Mumbai', 'Bangalore', 'Chennai'], dtype=object)

In [185]:
df["City"].nunique()

5

In [186]:
df["Category"].unique()

array(['Electronics', 'Fashion', 'Accessories'], dtype=object)

In [187]:
df["Category"].nunique()

3

In [188]:
df["Payment_Method"].unique()

array(['UPI', 'Card', 'Cash'], dtype=object)

In [189]:
df["Payment_Method"].nunique()

3

In [190]:
df["Product"].unique()

array(['Laptop', 'Headphones', 'Shoes', 'T-Shirt', 'Smartphone', 'Jeans',
       'Watch', 'Keyboard', 'Backpack', 'Dress', 'Mouse', 'Sunglasses',
       'Monitor', 'Smartwatch', 'Wallet', 'Tablet'], dtype=object)

In [191]:
df["Product"].nunique()

16

In [192]:
df[df.duplicated()]

,Order_ID,Customer,Age,Gender,City,Product,Category,Price,Quantity,Payment_Method,Order_Date
20,O005,Arjun,27.0,Male,Bangalore,Smartphone,Electronics,28000.0,1,Card,2026-01-15

In [193]:
df.duplicated().sum()

np.int64(1)

In [194]:
df.shape

(21, 11)

In [195]:
df = df.drop_duplicates()

In [196]:
df.shape

(20, 11)

In [197]:
df[["Age", "Price", "Quantity"]].dtypes

Age         float64
Price       float64
Quantity      int64
dtype: object

In [198]:
df['Age'] = df['Age'].astype(int)
df['Price'] = df['Price'].astype(int)
df['Quantity'] = df['Quantity'].astype(int)

In [199]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"],errors="coerce")

In [200]:
df["Order_Date"].dt.year

0     2026.0
1     2026.0
2     2026.0
3     2026.0
4     2026.0
5     2026.0
6     2026.0
7        NaN
8     2026.0
9     2026.0
10    2026.0
11    2026.0
12    2026.0
13    2026.0
14    2026.0
15    2026.0
16    2026.0
17    2026.0
18    2026.0
19    2026.0
Name: Order_Date, dtype: float64

In [201]:
df["Order_Date"].dt.month

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     NaN
8     1.0
9     1.0
10    2.0
11    2.0
12    2.0
13    2.0
14    2.0
15    2.0
16    2.0
17    2.0
18    2.0
19    2.0
Name: Order_Date, dtype: float64

In [202]:
df[df["Order_Date"] > "2026-02-01"]

,Order_ID,Customer,Age,Gender,City,Product,Category,Price,Quantity,Payment_Method,Order_Date
10,O011,Dev,27,Male,Delhi,Mouse,Electronics,1200,3,UPI,2026-02-02
11,O012,Riya,30,Female,Mumbai,Sunglasses,Accessories,1800,2,Card,2026-02-05
12,O013,Karan,33,Male,Kolkata,Monitor,Electronics,14000,1,UPI,2026-02-08
13,O014,Tanya,22,Female,Chennai,T-Shirt,Fashion,900,2,Cash,2026-02-10
14,O015,Manish,38,Male,Bangalore,Shoes,Fashion,3500,1,Card,2026-02-13
15,O016,Simran,27,Female,Delhi,Smartwatch,Electronics,6500,1,UPI,2026-02-16
16,O017,Aditya,24,Male,Mumbai,Wallet,Accessories,1000,2,Cash,2026-02-18
17,O018,Meera,29,Female,Kolkata,Tablet,Electronics,22000,1,Card,2026-02-21
18,O019,Sahil,32,Male,Chennai,Jeans,Fashion,1900,2,UPI,2026-02-24
19,O020,Anjali,26,Female,Bangalore,Headphones,Electronics,2800,1,Card,2026-02-27

In [203]:
df["Order_Date"].max()

Timestamp('2026-02-27 00:00:00')

In [204]:
df["Order_Date"].min()

Timestamp('2026-01-05 00:00:00')

In [205]:
df = pd.merge(df, city_df, on="City")

In [206]:
df.shape

(20, 14)

In [207]:
df = pd.concat([df, order_df], ignore_index=True)

In [208]:
df.shape

(25, 14)

In [209]:
df["City"].value_counts().idxmax()

'Kolkata'

In [210]:
df.groupby("Category")["Price"].mean().idxmax()

'Electronics'

In [211]:
df.loc[df["Price"].idxmax(), ["Product", "Price"]]

Product    Laptop
Price       55000
Name: 0, dtype: object

In [213]:
df["Gender"].value_counts()

Gender
Male      10
Female    10
M          3
F          2
Name: count, dtype: int64

In [214]:
df["Age"].mean()

np.float64(27.08)

In [215]:
df["Total_Sales"] = df["Price"] * df["Quantity"]