<a href="https://colab.research.google.com/github/armansayed41-ship-it/Road-to-ML-Engineer/blob/main/pandas_day_07_and08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
import pandas as pd
df = pd.read_csv("/content/student_performance_analysis_dataset.csv")

In [31]:
total_student = df["Student_ID"].count()
print(total_student)

20

In [32]:
df.shape[1]

12

In [33]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Study_Hours',
       'Attendance', 'Assignment_Score', 'Quiz_Score', 'Exam_Score',
       'Projects', 'Result'],
      dtype='object')

In [34]:
df.dtypes

Student_ID          object
Name                object
Age                  int64
Gender              object
Department          object
Study_Hours          int64
Attendance           int64
Assignment_Score     int64
Quiz_Score           int64
Exam_Score           int64
Projects             int64
Result              object
dtype: object

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df[df["Study_Hours"] > 5 ]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignment_Score,Quiz_Score,Exam_Score,Projects,Result
2,S003,Aman,20,Male,CSE,7,92,90,88,91,4,Pass
4,S005,Arjun,22,Male,IT,6,85,84,80,79,3,Pass
8,S009,Vikas,24,Male,CSE,8,95,92,91,94,5,Pass
11,S012,Riya,21,Female,CSE,6,87,85,82,88,4,Pass
14,S015,Manish,24,Male,IT,7,91,89,86,90,4,Pass
17,S018,Meera,20,Female,IT,6,89,86,84,85,3,Pass

In [37]:
df[(df["Study_Hours"] > 5) & (df["Exam_Score"] > 80) ]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignment_Score,Quiz_Score,Exam_Score,Projects,Result
2,S003,Aman,20,Male,CSE,7,92,90,88,91,4,Pass
8,S009,Vikas,24,Male,CSE,8,95,92,91,94,5,Pass
11,S012,Riya,21,Female,CSE,6,87,85,82,88,4,Pass
14,S015,Manish,24,Male,IT,7,91,89,86,90,4,Pass
17,S018,Meera,20,Female,IT,6,89,86,84,85,3,Pass

In [38]:
df[df["Department"] == "CSE"]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignment_Score,Quiz_Score,Exam_Score,Projects,Result
0,S001,Rahul,20,Male,CSE,5,88,82,78,85,3,Pass
2,S003,Aman,20,Male,CSE,7,92,90,88,91,4,Pass
5,S006,Neha,21,Female,CSE,4,81,75,70,73,2,Pass
8,S009,Vikas,24,Male,CSE,8,95,92,91,94,5,Pass
11,S012,Riya,21,Female,CSE,6,87,85,82,88,4,Pass
15,S016,Simran,22,Female,CSE,5,84,80,79,81,3,Pass
18,S019,Sahil,23,Male,CSE,3,71,65,63,60,2,Pass

In [39]:
df[df["Department"] == "IT"]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignment_Score,Quiz_Score,Exam_Score,Projects,Result
1,S002,Priya,21,Female,IT,3,76,70,72,68,2,Pass
4,S005,Arjun,22,Male,IT,6,85,84,80,79,3,Pass
7,S008,Isha,20,Female,IT,5,90,88,85,87,3,Pass
10,S011,Dev,22,Male,IT,4,79,73,76,70,2,Pass
14,S015,Manish,24,Male,IT,7,91,89,86,90,4,Pass
17,S018,Meera,20,Female,IT,6,89,86,84,85,3,Pass

In [40]:
df[df["Result"] == "Fail"]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignment_Score,Quiz_Score,Exam_Score,Projects,Result
3,S004,Sneha,19,Female,ECE,2,65,60,55,48,1,Fail
6,S007,Rohit,23,Male,ME,2,58,55,50,45,1,Fail
13,S014,Tanya,20,Female,ECE,1,52,48,45,40,1,Fail

In [41]:
df[df["Attendance"] <= 70]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignment_Score,Quiz_Score,Exam_Score,Projects,Result
3,S004,Sneha,19,Female,ECE,2,65,60,55,48,1,Fail
6,S007,Rohit,23,Male,ME,2,58,55,50,45,1,Fail
12,S013,Karan,23,Male,ME,3,68,62,58,55,1,Pass
13,S014,Tanya,20,Female,ECE,1,52,48,45,40,1,Fail

In [42]:
df["Study_Hours"].mean()

np.float64(4.45)

In [43]:
df["Attendance"].mean()

np.float64(79.0)

In [44]:
df["Exam_Score"].mean()

np.float64(72.15)

In [45]:
df["Exam_Score"].max()

94

In [46]:
df["Exam_Score"].min()

40

In [47]:
df.groupby("Department")["Exam_Score"].mean()

Department
CSE    81.714286
ECE    56.750000
IT     79.833333
ME     55.000000
Name: Exam_Score, dtype: float64

In [48]:
df.groupby("Department")["Attendance"].mean()

Department
CSE    85.428571
ECE    68.000000
IT     85.000000
ME     66.666667
Name: Attendance, dtype: float64

In [49]:
df.groupby("Department")["Student_ID"].count()

Department
CSE    7
ECE    4
IT     6
ME     3
Name: Student_ID, dtype: int64

In [50]:
df.groupby("Department")["Result"].value_counts().unstack(fill_value=0)

Result      Fail  Pass
Department
CSE            0     7
ECE            2     2
IT             0     6
ME             1     2

In [51]:
df.loc[df["Exam_Score"].idxmax(), "Name"]

'Vikas'

In [52]:
df.loc[df["Exam_Score"].idxmin(), "Name"]

'Tanya'

In [53]:
df.loc[df["Attendance"].idxmax(), "Name"]

'Vikas'

In [54]:
df.loc[df["Study_Hours"].idxmax(), "Name"]

'Vikas'

In [57]:
def performance(score):
  if score >= 85:
    return "Excellent"
  elif score >= 70:
    return "Good"
  elif score >= 50:
    return "Average"
  else:
    return "Poor"
df["Performance"] = df["Exam_Score"].apply(performance)
print(df)

   Student_ID    Name  Age  Gender Department  Study_Hours  Attendance  \
0        S001   Rahul   20    Male        CSE            5          88
1        S002   Priya   21  Female         IT            3          76
2        S003    Aman   20    Male        CSE            7          92
3        S004   Sneha   19  Female        ECE            2          65
4        S005   Arjun   22    Male         IT            6          85
5        S006    Neha   21  Female        CSE            4          81
6        S007   Rohit   23    Male         ME            2          58
7        S008    Isha   20  Female         IT            5          90
8        S009   Vikas   24    Male        CSE            8          95
9        S010   Pooja   19  Female        ECE            3          72
10       S011     Dev   22    Male         IT            4          79
11       S012    Riya   21  Female        CSE            6          87
12       S013   Karan   23    Male         ME            3          68
13       S014   Tanya   20  Female        ECE            1          52
14       S015  Manish   24    Male         IT            7          91
15       S016  Simran   22  Female        CSE            5          84
16       S017  Aditya   21    Male         ME            4          74
17       S018   Meera   20  Female         IT            6          89
18       S019   Sahil   23    Male        CSE            3          71
19       S020  Anjali   21  Female        ECE            5          83

    Assignment_Score  Quiz_Score  Exam_Score  Projects Result Performance
0                 82          78          85         3   Pass   Excellent
1                 70          72          68         2   Pass     Average
2                 90          88          91         4   Pass   Excellent
3                 60          55          48         1   Fail        Poor
4                 84          80          79         3   Pass        Good
5                 75          70          73         2   Pass        Good
6                 55          50          45         1   Fail        Poor
7                 88          85          87         3   Pass   Excellent
8                 92          91          94         5   Pass   Excellent
9                 68          65          62         2   Pass     Average
10                73          76          70         2   Pass        Good
11                85          82          88         4   Pass   Excellent
12                62          58          55         1   Pass     Average
13                48          45          40         1   Fail        Poor
14                89          86          90         4   Pass   Excellent
15                80          79          81         3   Pass        Good
16                70          68          65         2   Pass     Average
17                86          84          85         3   Pass   Excellent
18                65          63          60         2   Pass     Average
19                78          75          77         3   Pass        Good

In [59]:
df["Total_Score"] = df["Assignment_Score"] + df["Quiz_Score"] + df["Exam_Score"]

In [65]:
df.sort_values("Total_Score",ascending=False)["Name"].head(5)

8      Vikas
2       Aman
14    Manish
7       Isha
17     Meera
Name: Name, dtype: object

In [79]:
corr = df[["Study_Hours" , "Attendance", "Exam_Score"]].corr()
corr = corr.where(corr < 1)
pair = corr.stack().idxmax()
highest = corr.stack().max()
print("Pair", pair)
print("Correlation", highest)

Pair ('Attendance', 'Exam_Score')
Correlation 0.9901580985586186

In [82]:
df.groupby("Department")["Exam_Score"].mean().idxmax()

81.71428571428571

In [85]:
df.groupby("Department")["Student_ID"].count().idxmax()

'CSE'

In [87]:
df.loc[df["Total_Score"].idxmax(), "Name"]

'Vikas'

In [88]:
df.groupby("Result")["Exam_Score"].mean()

Result
Fail    44.333333
Pass    77.058824
Name: Exam_Score, dtype: float64

In [91]:
arr = np.array([10, 20, 30, 40, 50])

In [94]:
sum = np.sum(arr)
print(sum)

150

In [95]:
average = np.mean(arr)
print(average)

30.0

In [96]:
highest = np.max(arr)
print(highest)

50

In [97]:
lowest = np.min(arr)
print(lowest)

10

In [98]:
arr1 = np.array([5, 10, 15, 20, 25])

In [101]:
arr1 + 5

array([10, 15, 20, 25, 30])

In [102]:
arr1 - 5

array([ 0,  5, 10, 15, 20])

In [103]:
arr1 * 2

array([10, 20, 30, 40, 50])

In [104]:
arr1 / 5

array([1., 2., 3., 4., 5.])

In [106]:
arr2 = np.array([10, 15, 22, 31, 40, 55, 60, 73])

In [111]:
even = arr2[arr2 % 2 == 0]
print(even)

[10 22 40 60]

In [113]:
arr2[arr2 >= 50]

array([55, 60, 73])

In [116]:
np.argmax(arr2)

np.int64(7)

In [117]:
np.argmin(arr2)

np.int64(0)

In [121]:
arr3 = np.arange(1, 13)
arr3 = arr3.reshape(3, 4)
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

In [122]:
arr4 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [123]:
np.sum(arr4)

np.int64(450)

In [124]:
np.mean(arr4)

np.float64(50.0)

In [125]:
np.max(arr4)

np.int64(90)

In [126]:
np.min(arr4)

np.int64(10)

In [127]:
np.sum(arr4, axis = 1)

array([ 60, 150, 240])

In [128]:
np.sum(arr4, axis = 0)

array([120, 150, 180])

In [129]:
marks = np.array([45, 78, 92, 56, 88, 39, 67, 95])

In [130]:
marks[marks >= 80]

array([92, 88, 95])

In [131]:
marks[marks < 50]

array([45, 39])

In [133]:
marks[(marks < 50) & (marks < 80)]

array([45, 39])

In [134]:
np.where(marks >= 50, "Pass", "Fail")

array(['Fail', 'Pass', 'Pass', 'Pass', 'Pass', 'Fail', 'Pass', 'Pass'],
      dtype='<U4')

In [135]:
marks1 = np.array([45, 78, 92, 56, 88, 39, 67, 95, 72, 81])

In [138]:
np.mean(marks1)

np.float64(71.3)

In [139]:
np.max(marks1)

np.int64(95)

In [140]:
np.min(marks1)

np.int64(39)

In [141]:
np.argmax(marks1)

np.int64(7)

In [146]:
np.sum(marks1 >= 80)

np.int64(4)

In [147]:
np.sum(marks1 < 50)

np.int64(2)

In [148]:
passed = np.sum(marks1 >= 50)
total = len(marks1)

percentage = (passed / total) * 100

print(percentage)

80.0

In [149]:
scores = df["Exam_Score"].to_numpy()

In [150]:
np.mean(scores)

np.float64(72.15)

In [151]:
np.max(scores)

np.int64(94)

In [152]:
np.min(scores)

np.int64(40)

In [154]:
scores[scores >= 80]

array([85, 91, 87, 94, 88, 90, 81, 85])

In [155]:
scores[scores < 50]

array([48, 45, 40])