<a href="https://colab.research.google.com/github/armansayed41-ship-it/Road-to-ML-Engineer/blob/main/pandas_day_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [126]:
import pandas as pd
df = pd.read_csv("/content/employee_dataset.csv")
departments = pd.read_csv("/content/departments.csv")
employees = pd.read_csv("/content/new_employees.csv")
print(df)

   Employee_ID    Name   Age  Gender Department   Salary Joining_Date  \
0         E001   Rahul  22.0       M         IT  25000.0   2025-01-15
1         E002   Priya  24.0       F         HR  28000.0   2025-02-10
2         E003    Aman   NaN    Male         IT  32000.0   2025-03-05
3         E004   Sneha  23.0  Female    Finance      NaN   2025-03-18
4         E005   Arjun  27.0       M         IT  45000.0   2025-04-12
5         E006    Neha  25.0       F         HR  30000.0          NaN
6         E007   Rohit  29.0    male    Finance  38000.0   2025-05-20
7         E008    Isha  21.0       F         IT  22000.0   2025-06-01
8         E009   Vikas  31.0    Male      Sales  41000.0   2025-06-15
9         E010   Pooja  26.0       F         HR  35000.0   2025-07-10
10        E011     Dev   NaN       M         IT  29000.0   2025-07-25
11        E012    Riya  28.0  Female      Sales  39000.0   2025-08-05
12        E013   Karan  33.0       M    Finance  50000.0   2025-08-18
13        E014   Tanya  22.0       F      Sales      NaN   2025-09-01
14        E015  Manish  38.0    Male         IT  55000.0   2025-09-15
15        E016  Simran  27.0       F         HR  33000.0   2025-10-01
16        E017  Aditya  24.0       M         IT  26000.0   2025-10-12
17        E018   Meera  29.0  Female    Finance  42000.0          NaN
18        E019   Sahil  32.0       M      Sales  46000.0   2025-11-05
19        E020  Anjali  26.0       F         HR  34000.0   2025-11-20
20        E005   Arjun  27.0       M         IT  45000.0   2025-04-12

         City
0     Kolkata
1       Delhi
2      Mumbai
3     Kolkata
4   Bangalore
5       Delhi
6      Mumbai
7     Kolkata
8     Chennai
9   Bangalore
10      Delhi
11     Mumbai
12    Kolkata
13    Chennai
14  Bangalore
15      Delhi
16     Mumbai
17    Kolkata
18    Chennai
19  Bangalore
20  Bangalore

In [127]:
df = df.drop(columns=["City"])

In [128]:
df.isnull().sum()

Employee_ID     0
Name            0
Age             2
Gender          0
Department      0
Salary          2
Joining_Date    2
dtype: int64

In [129]:
df.dropna()

   Employee_ID    Name   Age  Gender Department   Salary Joining_Date
0         E001   Rahul  22.0       M         IT  25000.0   2025-01-15
1         E002   Priya  24.0       F         HR  28000.0   2025-02-10
4         E005   Arjun  27.0       M         IT  45000.0   2025-04-12
6         E007   Rohit  29.0    male    Finance  38000.0   2025-05-20
7         E008    Isha  21.0       F         IT  22000.0   2025-06-01
8         E009   Vikas  31.0    Male      Sales  41000.0   2025-06-15
9         E010   Pooja  26.0       F         HR  35000.0   2025-07-10
11        E012    Riya  28.0  Female      Sales  39000.0   2025-08-05
12        E013   Karan  33.0       M    Finance  50000.0   2025-08-18
14        E015  Manish  38.0    Male         IT  55000.0   2025-09-15
15        E016  Simran  27.0       F         HR  33000.0   2025-10-01
16        E017  Aditya  24.0       M         IT  26000.0   2025-10-12
18        E019   Sahil  32.0       M      Sales  46000.0   2025-11-05
19        E020  Anjali  26.0       F         HR  34000.0   2025-11-20
20        E005   Arjun  27.0       M         IT  45000.0   2025-04-12

In [130]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [131]:
df["Salary"] = df["Salary"].fillna(0)

In [132]:
df["Joining_Date"] = df["Joining_Date"].fillna("Unknown")

In [133]:
df["Gender"] = df["Gender"].replace("M","Male")
df["Gender"] = df["Gender"].replace("male","Male")
df["Gender"] = df["Gender"].replace("F","Female")

In [134]:
df = df.rename(columns={"Employee_ID": "ID", "Joining_Date": "Join_Date", "Department": "Dept"})

In [135]:
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [136]:
df["Gender"].nunique()

2

In [137]:
df["Dept"].unique()

array(['IT', 'HR', 'Finance', 'Sales'], dtype=object)

In [138]:
df["Dept"].nunique()

4

In [139]:
df[df.duplicated()]

      ID   Name   Age Gender Dept   Salary   Join_Date
20  E005  Arjun  27.0   Male   IT  45000.0  2025-04-12

In [140]:
df.duplicated().sum()

np.int64(1)

In [141]:
df.shape

(21, 7)

In [142]:
df = df.drop_duplicates()

In [143]:
df.shape

(20, 7)

In [144]:
df["Age"].dtype

dtype('float64')

In [145]:
df["Age"] = df["Age"].astype(int)

In [146]:
df["Age"].dtype

dtype('int64')

In [147]:
df["Salary"].dtype

dtype('float64')

In [148]:
df["Salary"] = df["Salary"].astype(int)

In [149]:
df["Salary"].dtype

dtype('int64')

In [150]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")
df["Join_Date"].dt.year

0     2025.0
1     2025.0
2     2025.0
3     2025.0
4     2025.0
5        NaN
6     2025.0
7     2025.0
8     2025.0
9     2025.0
10    2025.0
11    2025.0
12    2025.0
13    2025.0
14    2025.0
15    2025.0
16    2025.0
17       NaN
18    2025.0
19    2025.0
Name: Join_Date, dtype: float64

In [151]:
df["Join_Date"].dt.month

0      1.0
1      2.0
2      3.0
3      3.0
4      4.0
5      NaN
6      5.0
7      6.0
8      6.0
9      7.0
10     7.0
11     8.0
12     8.0
13     9.0
14     9.0
15    10.0
16    10.0
17     NaN
18    11.0
19    11.0
Name: Join_Date, dtype: float64

In [152]:
df[df["Join_Date"] > "2025-06-01"]

      ID    Name  Age  Gender     Dept  Salary  Join_Date
8   E009   Vikas   31    Male    Sales   41000 2025-06-15
9   E010   Pooja   26  Female       HR   35000 2025-07-10
10  E011     Dev   27    Male       IT   29000 2025-07-25
11  E012    Riya   28  Female    Sales   39000 2025-08-05
12  E013   Karan   33    Male  Finance   50000 2025-08-18
13  E014   Tanya   22  Female    Sales       0 2025-09-01
14  E015  Manish   38    Male       IT   55000 2025-09-15
15  E016  Simran   27  Female       HR   33000 2025-10-01
16  E017  Aditya   24    Male       IT   26000 2025-10-12
18  E019   Sahil   32    Male    Sales   46000 2025-11-05
19  E020  Anjali   26  Female       HR   34000 2025-11-20

In [153]:
pd.merge(employees, departments, on="Department")

,Employee_ID,Name,Age,Gender,Department,Salary,Joining_Date,City,Manager,Location
0,E021,Varun,23,M,Marketing,27000,2025-12-01,Kolkata,Arun,Bangalore
1,E022,Kavya,25,F,Marketing,31000,2025-12-05,Delhi,Arun,Bangalore
2,E023,Harsh,28,M,Sales,37000,2025-12-10,Mumbai,Meena,Chennai
3,E024,Nisha,24,F,IT,29000,2025-12-15,Bangalore,Rajesh,Kolkata
4,E025,Yash,30,M,Finance,44000,2025-12-20,Chennai,Suresh,Mumbai

In [154]:
pd.concat([df, employees])

,ID,Name,Age,Gender,Dept,Salary,Join_Date,Employee_ID,Department,Joining_Date,City
0,E001,Rahul,22,Male,IT,25000,2025-01-15,NaN,NaN,NaN,NaN
1,E002,Priya,24,Female,HR,28000,2025-02-10,NaN,NaN,NaN,NaN
2,E003,Aman,27,Male,IT,32000,2025-03-05,NaN,NaN,NaN,NaN
3,E004,Sneha,23,Female,Finance,0,2025-03-18,NaN,NaN,NaN,NaN
4,E005,Arjun,27,Male,IT,45000,2025-04-12,NaN,NaN,NaN,NaN
5,E006,Neha,25,Female,HR,30000,NaT,NaN,NaN,NaN,NaN
6,E007,Rohit,29,Male,Finance,38000,2025-05-20,NaN,NaN,NaN,NaN
7,E008,Isha,21,Female,IT,22000,2025-06-01,NaN,NaN,NaN,NaN
8,E009,Vikas,31,Male,Sales,41000,2025-06-15,NaN,NaN,NaN,NaN
9,E010,Pooja,26,Female,HR,35000,2025-07-10,NaN,NaN,NaN,NaN
10,E011,Dev,27,Male,IT,29000,2025-07-25,NaN,NaN,NaN,NaN
11,E012,Riya,28,Female,Sales,39000,2025-08-05,NaN,NaN,NaN,NaN
12,E013,Karan,33,Male,Finance,50000,2025-08-18,NaN,NaN,NaN,NaN
13,E014,Tanya,22,Female,Sales,0,2025-09-01,NaN,NaN,NaN,NaN
14,E015,Manish,38,Male,IT,55000,2025-09-15,NaN,NaN,NaN,NaN
15,E016,Simran,27,Female,HR,33000,2025-10-01,NaN,NaN,NaN,NaN
16,E017,Aditya,24,Male,IT,26000,2025-10-12,NaN,NaN,NaN,NaN
17,E018,Meera,29,Female,Finance,42000,NaT,NaN,NaN,NaN,NaN
18,E019,Sahil,32,Male,Sales,46000,2025-11-05,NaN,NaN,NaN,NaN
19,E020,Anjali,26,Female,HR,34000,2025-11-20,NaN,NaN,NaN,NaN
0,NaN,Varun,23,M,NaN,27000,NaT,E021,Marketing,2025-12-01,Kolkata
1,NaN,Kavya,25,F,NaN,31000,NaT,E022,Marketing,2025-12-05,Delhi
2,NaN,Harsh,28,M,NaN,37000,NaT,E023,Sales,2025-12-10,Mumbai
3,NaN,Nisha,24,F,NaN,29000,NaT,E024,IT,2025-12-15,Bangalore
4,NaN,Yash,30,M,NaN,44000,NaT,E025,Finance,2025-12-20,Chennai