<a href="https://colab.research.google.com/github/armansayed41-ship-it/Road-to-ML-Engineer/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df = pd.read_csv("/content/ecommerce_sales_dataset.csv")
print(df)

   Order_ID Customer  Age Gender       City     Product     Category  Price  \
0      O001    Rahul   22      M    Kolkata      Laptop  Electronics  55000
1      O002    Priya   25      F      Delhi  Headphones  Electronics   2500
2      O003     Aman   29      M     Mumbai       Shoes      Fashion   3200
3      O004    Sneha   21      F    Kolkata     T-Shirt      Fashion    800
4      O005    Arjun   31      M  Bangalore  Smartphone  Electronics  28000
5      O006     Neha   24      F      Delhi       Jeans      Fashion   1800
6      O007    Rohit   27      M     Mumbai       Watch  Accessories   4500
7      O008     Isha   23      F    Kolkata    Keyboard  Electronics   2200
8      O009    Vikas   35      M    Chennai    Backpack  Accessories   1500
9      O010    Pooja   28      F  Bangalore       Dress      Fashion   2500
10     O011      Dev   26      M      Delhi       Mouse  Electronics   1200
11     O012     Riya   30      F     Mumbai  Sunglasses  Accessories   1800
12     O013    Karan   33      M    Kolkata     Monitor  Electronics  14000
13     O014    Tanya   22      F    Chennai     T-Shirt      Fashion    900
14     O015   Manish   38      M  Bangalore       Shoes      Fashion   3500
15     O016   Simran   27      F      Delhi  Smartwatch  Electronics   6500
16     O017   Aditya   24      M     Mumbai      Wallet  Accessories   1000
17     O018    Meera   29      F    Kolkata      Tablet  Electronics  22000
18     O019    Sahil   32      M    Chennai       Jeans      Fashion   1900
19     O020   Anjali   26      F  Bangalore  Headphones  Electronics   2800

    Quantity Payment_Method  Order_Date
0          1            UPI  2026-01-05
1          2           Card  2026-01-07
2          1            UPI  2026-01-10
3          3           Cash  2026-01-12
4          1           Card  2026-01-15
5          2            UPI  2026-01-18
6          1           Card  2026-01-20
7          1            UPI  2026-01-22
8          2           Cash  2026-01-25
9          1           Card  2026-01-28
10         3            UPI  2026-02-02
11         2           Card  2026-02-05
12         1            UPI  2026-02-08
13         2           Cash  2026-02-10
14         1           Card  2026-02-13
15         1            UPI  2026-02-16
16         2           Cash  2026-02-18
17         1           Card  2026-02-21
18         2            UPI  2026-02-24
19         1           Card  2026-02-27

In [4]:
df.shape

(20, 11)

In [5]:
df.columns

Index(['Order_ID', 'Customer', 'Age', 'Gender', 'City', 'Product', 'Category',
       'Price', 'Quantity', 'Payment_Method', 'Order_Date'],
      dtype='object')

In [7]:
df.dtypes

Order_ID          object
Customer          object
Age                int64
Gender            object
City              object
Product           object
Category          object
Price              int64
Quantity           int64
Payment_Method    object
Order_Date        object
dtype: object

In [10]:
df.isnull().sum()

Order_ID          0
Customer          0
Age               0
Gender            0
City              0
Product           0
Category          0
Price             0
Quantity          0
Payment_Method    0
Order_Date        0
dtype: int64

In [12]:
df[df["Price"] > 5000]

,Order_ID,Customer,Age,Gender,City,Product,Category,Price,Quantity,Payment_Method,Order_Date
0,O001,Rahul,22,M,Kolkata,Laptop,Electronics,55000,1,UPI,2026-01-05
4,O005,Arjun,31,M,Bangalore,Smartphone,Electronics,28000,1,Card,2026-01-15
12,O013,Karan,33,M,Kolkata,Monitor,Electronics,14000,1,UPI,2026-02-08
15,O016,Simran,27,F,Delhi,Smartwatch,Electronics,6500,1,UPI,2026-02-16
17,O018,Meera,29,F,Kolkata,Tablet,Electronics,22000,1,Card,2026-02-21

In [19]:
df[(df["Age"]) > 25 & (df["Quantity"] >=2)]

,Order_ID,Customer,Age,Gender,City,Product,Category,Price,Quantity,Payment_Method,Order_Date
0,O001,Rahul,22,M,Kolkata,Laptop,Electronics,55000,1,UPI,2026-01-05
1,O002,Priya,25,F,Delhi,Headphones,Electronics,2500,2,Card,2026-01-07
2,O003,Aman,29,M,Mumbai,Shoes,Fashion,3200,1,UPI,2026-01-10
3,O004,Sneha,21,F,Kolkata,T-Shirt,Fashion,800,3,Cash,2026-01-12
4,O005,Arjun,31,M,Bangalore,Smartphone,Electronics,28000,1,Card,2026-01-15
5,O006,Neha,24,F,Delhi,Jeans,Fashion,1800,2,UPI,2026-01-18
6,O007,Rohit,27,M,Mumbai,Watch,Accessories,4500,1,Card,2026-01-20
7,O008,Isha,23,F,Kolkata,Keyboard,Electronics,2200,1,UPI,2026-01-22
8,O009,Vikas,35,M,Chennai,Backpack,Accessories,1500,2,Cash,2026-01-25
9,O010,Pooja,28,F,Bangalore,Dress,Fashion,2500,1,Card,2026-01-28
10,O011,Dev,26,M,Delhi,Mouse,Electronics,1200,3,UPI,2026-02-02
11,O012,Riya,30,F,Mumbai,Sunglasses,Accessories,1800,2,Card,2026-02-05
12,O013,Karan,33,M,Kolkata,Monitor,Electronics,14000,1,UPI,2026-02-08
13,O014,Tanya,22,F,Chennai,T-Shirt,Fashion,900,2,Cash,2026-02-10
14,O015,Manish,38,M,Bangalore,Shoes,Fashion,3500,1,Card,2026-02-13
15,O016,Simran,27,F,Delhi,Smartwatch,Electronics,6500,1,UPI,2026-02-16
16,O017,Aditya,24,M,Mumbai,Wallet,Accessories,1000,2,Cash,2026-02-18
17,O018,Meera,29,F,Kolkata,Tablet,Electronics,22000,1,Card,2026-02-21
18,O019,Sahil,32,M,Chennai,Jeans,Fashion,1900,2,UPI,2026-02-24
19,O020,Anjali,26,F,Bangalore,Headphones,Electronics,2800,1,Card,2026-02-27

In [22]:
df[df["Category"] == "Electronics"]

,Order_ID,Customer,Age,Gender,City,Product,Category,Price,Quantity,Payment_Method,Order_Date
0,O001,Rahul,22,M,Kolkata,Laptop,Electronics,55000,1,UPI,2026-01-05
1,O002,Priya,25,F,Delhi,Headphones,Electronics,2500,2,Card,2026-01-07
4,O005,Arjun,31,M,Bangalore,Smartphone,Electronics,28000,1,Card,2026-01-15
7,O008,Isha,23,F,Kolkata,Keyboard,Electronics,2200,1,UPI,2026-01-22
10,O011,Dev,26,M,Delhi,Mouse,Electronics,1200,3,UPI,2026-02-02
12,O013,Karan,33,M,Kolkata,Monitor,Electronics,14000,1,UPI,2026-02-08
15,O016,Simran,27,F,Delhi,Smartwatch,Electronics,6500,1,UPI,2026-02-16
17,O018,Meera,29,F,Kolkata,Tablet,Electronics,22000,1,Card,2026-02-21
19,O020,Anjali,26,F,Bangalore,Headphones,Electronics,2800,1,Card,2026-02-27

In [24]:
df["Price"].sort_values(ascending = False).head(5)

0     55000
4     28000
17    22000
12    14000
15     6500
Name: Price, dtype: int64

In [26]:
df["Price"].mean()

np.float64(7880.0)

In [28]:
df["Price"].max()

55000

In [29]:
df["Price"].min()

800

In [30]:
df["Age"].mean()

np.float64(27.6)

In [31]:
df["Quantity"].sum()

np.int64(31)

In [34]:
df.groupby("Category")["Price"].mean()

Category
Accessories     2200.000000
Electronics    14911.111111
Fashion         2085.714286
Name: Price, dtype: float64

In [36]:
df.groupby("Category")["Quantity"].sum()

Category
Accessories     7
Electronics    12
Fashion        12
Name: Quantity, dtype: int64

In [40]:
df["City"].value_counts()

City
Kolkata      5
Delhi        4
Mumbai       4
Bangalore    4
Chennai      3
Name: count, dtype: int64

In [41]:
df["Gender"].value_counts()

Gender
M    10
F    10
Name: count, dtype: int64

In [42]:
df["Category"].value_counts()

Category
Electronics    9
Fashion        7
Accessories    4
Name: count, dtype: int64

In [50]:
df["City"].value_counts().idxmax()

'Kolkata'

In [45]:
df["Total_Sales"] = df["Price"] * df["Quantity"]
print(df)

   Order_ID Customer  Age Gender       City     Product     Category  Price  \
0      O001    Rahul   22      M    Kolkata      Laptop  Electronics  55000
1      O002    Priya   25      F      Delhi  Headphones  Electronics   2500
2      O003     Aman   29      M     Mumbai       Shoes      Fashion   3200
3      O004    Sneha   21      F    Kolkata     T-Shirt      Fashion    800
4      O005    Arjun   31      M  Bangalore  Smartphone  Electronics  28000
5      O006     Neha   24      F      Delhi       Jeans      Fashion   1800
6      O007    Rohit   27      M     Mumbai       Watch  Accessories   4500
7      O008     Isha   23      F    Kolkata    Keyboard  Electronics   2200
8      O009    Vikas   35      M    Chennai    Backpack  Accessories   1500
9      O010    Pooja   28      F  Bangalore       Dress      Fashion   2500
10     O011      Dev   26      M      Delhi       Mouse  Electronics   1200
11     O012     Riya   30      F     Mumbai  Sunglasses  Accessories   1800
12     O013    Karan   33      M    Kolkata     Monitor  Electronics  14000
13     O014    Tanya   22      F    Chennai     T-Shirt      Fashion    900
14     O015   Manish   38      M  Bangalore       Shoes      Fashion   3500
15     O016   Simran   27      F      Delhi  Smartwatch  Electronics   6500
16     O017   Aditya   24      M     Mumbai      Wallet  Accessories   1000
17     O018    Meera   29      F    Kolkata      Tablet  Electronics  22000
18     O019    Sahil   32      M    Chennai       Jeans      Fashion   1900
19     O020   Anjali   26      F  Bangalore  Headphones  Electronics   2800

    Quantity Payment_Method  Order_Date  Total_Sales
0          1            UPI  2026-01-05        55000
1          2           Card  2026-01-07         5000
2          1            UPI  2026-01-10         3200
3          3           Cash  2026-01-12         2400
4          1           Card  2026-01-15        28000
5          2            UPI  2026-01-18         3600
6          1           Card  2026-01-20         4500
7          1            UPI  2026-01-22         2200
8          2           Cash  2026-01-25         3000
9          1           Card  2026-01-28         2500
10         3            UPI  2026-02-02         3600
11         2           Card  2026-02-05         3600
12         1            UPI  2026-02-08        14000
13         2           Cash  2026-02-10         1800
14         1           Card  2026-02-13         3500
15         1            UPI  2026-02-16         6500
16         2           Cash  2026-02-18         2000
17         1           Card  2026-02-21        22000
18         2            UPI  2026-02-24         3800
19         1           Card  2026-02-27         2800

In [52]:
df.loc[df["Total_Sales"].idxmax()]

Order_ID                 O001
Customer                Rahul
Age                        22
Gender                      M
City                  Kolkata
Product                Laptop
Category          Electronics
Price                   55000
Quantity                    1
Payment_Method            UPI
Order_Date         2026-01-05
Total_Sales             55000
Name: 0, dtype: object

In [56]:
df.groupby("Category")["Total_Sales"].sum().idxmax()

'Electronics'

In [57]:
df["City"].value_counts().idxmax()

'Kolkata'

In [59]:
df.loc[df["Price"].idxmax(), "Product"]

'Laptop'

In [60]:
df["Total_Sales"].mean()

np.float64(8650.0)

In [62]:
df["Payment_Method"].value_counts().idxmax()

'UPI'

In [64]:
df.loc[df["Price"].idxmax(), "Customer"]

'Rahul'