<a href="https://colab.research.google.com/github/armansayed41-ship-it/Road-to-ML-Engineer/blob/main/pandas/day-01-and-02-pandas-basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv("/content/student_performance_dataset.csv")

In [ ]:
print(df)

   Student_ID    Name  Age Gender Department  Study_Hours  Attendance  \
0        S001   Rahul   18      M        CSE          4.5          88
1        S002   Priya   19      F        CSE          2.0          72
2        S003   Arjun   18      M         IT          1.5          65
3        S004   Sneha   20      F        CSE          5.0          94
4        S005    Aman   18      M         IT          3.0          79
5        S006  Anjali   19      F        ECE          4.0          85
6        S007   Rohit   20      M        CSE          2.5          68
7        S008    Neha   18      F         IT          4.5          91
8        S009  Vikash   19      M        ECE          3.5          77
9        S010   Pooja   20      F        CSE          1.0          61
10       S011  Aditya   18      M         IT          5.0          96
11       S012    Riya   19      F        ECE          3.0          82
12       S013   Karan   20      M        CSE          2.0          70
13       S014   Tanya   18      F         IT          4.0          89
14       S015  Manish   19      M        ECE          2.5          74
15       S016  Simran   20      F        CSE          4.5          93
16       S017     Dev   18      M         IT          1.5          63
17       S018    Isha   19      F        ECE          3.5          81
18       S019   Akash   20      M        CSE          3.0          76
19       S020   Meera   18      F         IT          5.0          97

    Assignments  Quiz_Score  Exam_Score  Projects Result
0             8          76          81         3   Pass
1             6          61          58         2   Pass
2             4          48          42         1   Fail
3            10          89          92         4   Pass
4             7          68          71         3   Pass
5             9          74          79         3   Pass
6             5          55          51         2   Fail
7             9          82          88         4   Pass
8             7          65          69         2   Pass
9             3          44          38         1   Fail
10           10          91          95         5   Pass
11            8          71          75         3   Pass
12            5          52          48         2   Fail
13            9          78          84         4   Pass
14            6          59          63         2   Pass
15           10          86          90         4   Pass
16            4          46          40         1   Fail
17            8          70          73         3   Pass
18            7          64          67         3   Pass
19           10          94          96         5   Pass

In [ ]:
df.head(5)

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result
0,S001,Rahul,18,M,CSE,4.5,88,8,76,81,3,Pass
1,S002,Priya,19,F,CSE,2.0,72,6,61,58,2,Pass
2,S003,Arjun,18,M,IT,1.5,65,4,48,42,1,Fail
3,S004,Sneha,20,F,CSE,5.0,94,10,89,92,4,Pass
4,S005,Aman,18,M,IT,3.0,79,7,68,71,3,Pass

In [ ]:
df.tail(5)

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result
15,S016,Simran,20,F,CSE,4.5,93,10,86,90,4,Pass
16,S017,Dev,18,M,IT,1.5,63,4,46,40,1,Fail
17,S018,Isha,19,F,ECE,3.5,81,8,70,73,3,Pass
18,S019,Akash,20,M,CSE,3.0,76,7,64,67,3,Pass
19,S020,Meera,18,F,IT,5.0,97,10,94,96,5,Pass

In [ ]:
df.shape

(20, 12)

In [ ]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Study_Hours',
       'Attendance', 'Assignments', 'Quiz_Score', 'Exam_Score', 'Projects',
       'Result'],
      dtype='object')

In [ ]:
df.dtypes

Student_ID      object
Name            object
Age              int64
Gender          object
Department      object
Study_Hours    float64
Attendance       int64
Assignments      int64
Quiz_Score       int64
Exam_Score       int64
Projects         int64
Result          object
dtype: object

In [ ]:
df.isnull().sum()

Student_ID     0
Name           0
Age            0
Gender         0
Department     0
Study_Hours    0
Attendance     0
Assignments    0
Quiz_Score     0
Exam_Score     0
Projects       0
Result         0
dtype: int64

In [ ]:
print("Students having marks greater then 80")
df[df["Exam_Score"] > 80]

Students having marks greater then 80

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result
0,S001,Rahul,18,M,CSE,4.5,88,8,76,81,3,Pass
3,S004,Sneha,20,F,CSE,5.0,94,10,89,92,4,Pass
7,S008,Neha,18,F,IT,4.5,91,9,82,88,4,Pass
10,S011,Aditya,18,M,IT,5.0,96,10,91,95,5,Pass
13,S014,Tanya,18,F,IT,4.0,89,9,78,84,4,Pass
15,S016,Simran,20,F,CSE,4.5,93,10,86,90,4,Pass
19,S020,Meera,18,F,IT,5.0,97,10,94,96,5,Pass

In [ ]:
print("Students having marks less then 70")
df[df["Exam_Score"] < 70]

Students having marks less then 70

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result
1,S002,Priya,19,F,CSE,2.0,72,6,61,58,2,Pass
2,S003,Arjun,18,M,IT,1.5,65,4,48,42,1,Fail
6,S007,Rohit,20,M,CSE,2.5,68,5,55,51,2,Fail
8,S009,Vikash,19,M,ECE,3.5,77,7,65,69,2,Pass
9,S010,Pooja,20,F,CSE,1.0,61,3,44,38,1,Fail
12,S013,Karan,20,M,CSE,2.0,70,5,52,48,2,Fail
14,S015,Manish,19,M,ECE,2.5,74,6,59,63,2,Pass
16,S017,Dev,18,M,IT,1.5,63,4,46,40,1,Fail
18,S019,Akash,20,M,CSE,3.0,76,7,64,67,3,Pass

In [ ]:
df[df["Result"] == "Fail"]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result
2,S003,Arjun,18,M,IT,1.5,65,4,48,42,1,Fail
6,S007,Rohit,20,M,CSE,2.5,68,5,55,51,2,Fail
9,S010,Pooja,20,F,CSE,1.0,61,3,44,38,1,Fail
12,S013,Karan,20,M,CSE,2.0,70,5,52,48,2,Fail
16,S017,Dev,18,M,IT,1.5,63,4,46,40,1,Fail

In [ ]:
df[df["Department"] == "CSE"]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result
0,S001,Rahul,18,M,CSE,4.5,88,8,76,81,3,Pass
1,S002,Priya,19,F,CSE,2.0,72,6,61,58,2,Pass
3,S004,Sneha,20,F,CSE,5.0,94,10,89,92,4,Pass
6,S007,Rohit,20,M,CSE,2.5,68,5,55,51,2,Fail
9,S010,Pooja,20,F,CSE,1.0,61,3,44,38,1,Fail
12,S013,Karan,20,M,CSE,2.0,70,5,52,48,2,Fail
15,S016,Simran,20,F,CSE,4.5,93,10,86,90,4,Pass
18,S019,Akash,20,M,CSE,3.0,76,7,64,67,3,Pass

In [ ]:
df[df["Study_Hours"] > 4]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result
0,S001,Rahul,18,M,CSE,4.5,88,8,76,81,3,Pass
3,S004,Sneha,20,F,CSE,5.0,94,10,89,92,4,Pass
7,S008,Neha,18,F,IT,4.5,91,9,82,88,4,Pass
10,S011,Aditya,18,M,IT,5.0,96,10,91,95,5,Pass
15,S016,Simran,20,F,CSE,4.5,93,10,86,90,4,Pass
19,S020,Meera,18,F,IT,5.0,97,10,94,96,5,Pass

In [ ]:
print("Students sorted by Exam Score:")

df.sort_values("Exam_Score", ascending=False)

Students sorted by Exam Score:

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result
19,S020,Meera,18,F,IT,5.0,97,10,94,96,5,Pass
10,S011,Aditya,18,M,IT,5.0,96,10,91,95,5,Pass
3,S004,Sneha,20,F,CSE,5.0,94,10,89,92,4,Pass
15,S016,Simran,20,F,CSE,4.5,93,10,86,90,4,Pass
7,S008,Neha,18,F,IT,4.5,91,9,82,88,4,Pass
13,S014,Tanya,18,F,IT,4.0,89,9,78,84,4,Pass
0,S001,Rahul,18,M,CSE,4.5,88,8,76,81,3,Pass
5,S006,Anjali,19,F,ECE,4.0,85,9,74,79,3,Pass
11,S012,Riya,19,F,ECE,3.0,82,8,71,75,3,Pass
17,S018,Isha,19,F,ECE,3.5,81,8,70,73,3,Pass
4,S005,Aman,18,M,IT,3.0,79,7,68,71,3,Pass
8,S009,Vikash,19,M,ECE,3.5,77,7,65,69,2,Pass
18,S019,Akash,20,M,CSE,3.0,76,7,64,67,3,Pass
14,S015,Manish,19,M,ECE,2.5,74,6,59,63,2,Pass
1,S002,Priya,19,F,CSE,2.0,72,6,61,58,2,Pass
6,S007,Rohit,20,M,CSE,2.5,68,5,55,51,2,Fail
12,S013,Karan,20,M,CSE,2.0,70,5,52,48,2,Fail
2,S003,Arjun,18,M,IT,1.5,65,4,48,42,1,Fail
16,S017,Dev,18,M,IT,1.5,63,4,46,40,1,Fail
9,S010,Pooja,20,F,CSE,1.0,61,3,44,38,1,Fail

In [ ]:
print("Top 5 Students:")

df.sort_values("Exam_Score", ascending=False).head(5)

Top 5 Students:

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result
19,S020,Meera,18,F,IT,5.0,97,10,94,96,5,Pass
10,S011,Aditya,18,M,IT,5.0,96,10,91,95,5,Pass
3,S004,Sneha,20,F,CSE,5.0,94,10,89,92,4,Pass
15,S016,Simran,20,F,CSE,4.5,93,10,86,90,4,Pass
7,S008,Neha,18,F,IT,4.5,91,9,82,88,4,Pass

In [ ]:
print("Average Exam Score:",df["Exam_Score"].mean())

Average Exam Score: 70.0

In [ ]:
print("Average attendance:",df["Attendance"].mean())

Average attendance: 80.05

In [ ]:
print("Average study hours:",df["Study_Hours"].mean())

Average study hours: 3.275

In [ ]:
print("Highest Exam Score:", df["Exam_Score"].max())

Highest Exam Score: 96

In [ ]:
print("Lowest Exam Score:", df["Exam_Score"].min())

Lowest Exam Score: 38

In [ ]:
df.groupby("Department")["Exam_Score"].mean()

Department
CSE    65.625000
ECE    71.800000
IT     73.714286
Name: Exam_Score, dtype: float64

In [ ]:
df.groupby("Department")["Attendance"].mean()

Department
CSE    77.750000
ECE    79.800000
IT     82.857143
Name: Attendance, dtype: float64

In [ ]:
df["Department"].value_counts()

Department
CSE    8
IT     7
ECE    5
Name: count, dtype: int64

In [ ]:
df["Result"].value_counts()

Result
Pass    15
Fail     5
Name: count, dtype: int64

In [ ]:
df[["Study_Hours", "Exam_Score"]]

    Study_Hours  Exam_Score
0           4.5          81
1           2.0          58
2           1.5          42
3           5.0          92
4           3.0          71
5           4.0          79
6           2.5          51
7           4.5          88
8           3.5          69
9           1.0          38
10          5.0          95
11          3.0          75
12          2.0          48
13          4.0          84
14          2.5          63
15          4.5          90
16          1.5          40
17          3.5          73
18          3.0          67
19          5.0          96

In [ ]:
df.groupby("Department")["Exam_Score"].mean().sort_values(ascending=False)

Department
IT     73.714286
ECE    71.800000
CSE    65.625000
Name: Exam_Score, dtype: float64

In [ ]:
df["Result"].value_counts(normalize=True) * 100

Result
Pass    75.0
Fail    25.0
Name: proportion, dtype: float64

In [ ]:
df.loc[df["Exam_Score"].idxmax()]

Student_ID      S020
Name           Meera
Age               18
Gender             F
Department        IT
Study_Hours      5.0
Attendance        97
Assignments       10
Quiz_Score        94
Exam_Score        96
Projects           5
Result          Pass
Name: 19, dtype: object

In [ ]:
df[df["Attendance"] < 70]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result
2,S003,Arjun,18,M,IT,1.5,65,4,48,42,1,Fail
6,S007,Rohit,20,M,CSE,2.5,68,5,55,51,2,Fail
9,S010,Pooja,20,F,CSE,1.0,61,3,44,38,1,Fail
16,S017,Dev,18,M,IT,1.5,63,4,46,40,1,Fail

In [ ]:
df[df["Study_Hours"] >= 4]["Exam_Score"].mean()

np.float64(88.125)

In [ ]:
def performance(score):
    if score >= 85:
        return "Excellent"
    elif score >= 70:
        return "Good"
    elif score >= 50:
        return "Average"
    else:
        return "Poor"

df["Performance"] = df["Exam_Score"].apply(performance)

print(df)

   Student_ID    Name  Age Gender Department  Study_Hours  Attendance  \
0        S001   Rahul   18      M        CSE          4.5          88
1        S002   Priya   19      F        CSE          2.0          72
2        S003   Arjun   18      M         IT          1.5          65
3        S004   Sneha   20      F        CSE          5.0          94
4        S005    Aman   18      M         IT          3.0          79
5        S006  Anjali   19      F        ECE          4.0          85
6        S007   Rohit   20      M        CSE          2.5          68
7        S008    Neha   18      F         IT          4.5          91
8        S009  Vikash   19      M        ECE          3.5          77
9        S010   Pooja   20      F        CSE          1.0          61
10       S011  Aditya   18      M         IT          5.0          96
11       S012    Riya   19      F        ECE          3.0          82
12       S013   Karan   20      M        CSE          2.0          70
13       S014   Tanya   18      F         IT          4.0          89
14       S015  Manish   19      M        ECE          2.5          74
15       S016  Simran   20      F        CSE          4.5          93
16       S017     Dev   18      M         IT          1.5          63
17       S018    Isha   19      F        ECE          3.5          81
18       S019   Akash   20      M        CSE          3.0          76
19       S020   Meera   18      F         IT          5.0          97

    Assignments  Quiz_Score  Exam_Score  Projects Result Performance
0             8          76          81         3   Pass        Good
1             6          61          58         2   Pass     Average
2             4          48          42         1   Fail        Poor
3            10          89          92         4   Pass   Excellent
4             7          68          71         3   Pass        Good
5             9          74          79         3   Pass        Good
6             5          55          51         2   Fail     Average
7             9          82          88         4   Pass   Excellent
8             7          65          69         2   Pass     Average
9             3          44          38         1   Fail        Poor
10           10          91          95         5   Pass   Excellent
11            8          71          75         3   Pass        Good
12            5          52          48         2   Fail        Poor
13            9          78          84         4   Pass        Good
14            6          59          63         2   Pass     Average
15           10          86          90         4   Pass   Excellent
16            4          46          40         1   Fail        Poor
17            8          70          73         3   Pass        Good
18            7          64          67         3   Pass     Average
19           10          94          96         5   Pass   Excellent

In [ ]:
df[(df["Attendance"] >= 85) & (df["Exam_Score"] >= 80)]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result,Performance
0,S001,Rahul,18,M,CSE,4.5,88,8,76,81,3,Pass,Good
3,S004,Sneha,20,F,CSE,5.0,94,10,89,92,4,Pass,Excellent
7,S008,Neha,18,F,IT,4.5,91,9,82,88,4,Pass,Excellent
10,S011,Aditya,18,M,IT,5.0,96,10,91,95,5,Pass,Excellent
13,S014,Tanya,18,F,IT,4.0,89,9,78,84,4,Pass,Good
15,S016,Simran,20,F,CSE,4.5,93,10,86,90,4,Pass,Excellent
19,S020,Meera,18,F,IT,5.0,97,10,94,96,5,Pass,Excellent

In [ ]:
df[(df["Department"] == "CSE") | (df["Department"] == "IT")]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result,Performance
0,S001,Rahul,18,M,CSE,4.5,88,8,76,81,3,Pass,Good
1,S002,Priya,19,F,CSE,2.0,72,6,61,58,2,Pass,Average
2,S003,Arjun,18,M,IT,1.5,65,4,48,42,1,Fail,Poor
3,S004,Sneha,20,F,CSE,5.0,94,10,89,92,4,Pass,Excellent
4,S005,Aman,18,M,IT,3.0,79,7,68,71,3,Pass,Good
6,S007,Rohit,20,M,CSE,2.5,68,5,55,51,2,Fail,Average
7,S008,Neha,18,F,IT,4.5,91,9,82,88,4,Pass,Excellent
9,S010,Pooja,20,F,CSE,1.0,61,3,44,38,1,Fail,Poor
10,S011,Aditya,18,M,IT,5.0,96,10,91,95,5,Pass,Excellent
12,S013,Karan,20,M,CSE,2.0,70,5,52,48,2,Fail,Poor
13,S014,Tanya,18,F,IT,4.0,89,9,78,84,4,Pass,Good
15,S016,Simran,20,F,CSE,4.5,93,10,86,90,4,Pass,Excellent
16,S017,Dev,18,M,IT,1.5,63,4,46,40,1,Fail,Poor
18,S019,Akash,20,M,CSE,3.0,76,7,64,67,3,Pass,Average
19,S020,Meera,18,F,IT,5.0,97,10,94,96,5,Pass,Excellent

In [ ]:
df[(df["Study_Hours"] >= 3) & (df["Attendance"] >= 80)]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result,Performance
0,S001,Rahul,18,M,CSE,4.5,88,8,76,81,3,Pass,Good
3,S004,Sneha,20,F,CSE,5.0,94,10,89,92,4,Pass,Excellent
5,S006,Anjali,19,F,ECE,4.0,85,9,74,79,3,Pass,Good
7,S008,Neha,18,F,IT,4.5,91,9,82,88,4,Pass,Excellent
10,S011,Aditya,18,M,IT,5.0,96,10,91,95,5,Pass,Excellent
11,S012,Riya,19,F,ECE,3.0,82,8,71,75,3,Pass,Good
13,S014,Tanya,18,F,IT,4.0,89,9,78,84,4,Pass,Good
15,S016,Simran,20,F,CSE,4.5,93,10,86,90,4,Pass,Excellent
17,S018,Isha,19,F,ECE,3.5,81,8,70,73,3,Pass,Good
19,S020,Meera,18,F,IT,5.0,97,10,94,96,5,Pass,Excellent

In [ ]:
df[df["Exam_Score"].between(60, 80)]

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result,Performance
4,S005,Aman,18,M,IT,3.0,79,7,68,71,3,Pass,Good
5,S006,Anjali,19,F,ECE,4.0,85,9,74,79,3,Pass,Good
8,S009,Vikash,19,M,ECE,3.5,77,7,65,69,2,Pass,Average
11,S012,Riya,19,F,ECE,3.0,82,8,71,75,3,Pass,Good
14,S015,Manish,19,M,ECE,2.5,74,6,59,63,2,Pass,Average
17,S018,Isha,19,F,ECE,3.5,81,8,70,73,3,Pass,Good
18,S019,Akash,20,M,CSE,3.0,76,7,64,67,3,Pass,Average

In [ ]:
df.sort_values("Attendance", ascending=False)

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result,Performance
19,S020,Meera,18,F,IT,5.0,97,10,94,96,5,Pass,Excellent
10,S011,Aditya,18,M,IT,5.0,96,10,91,95,5,Pass,Excellent
3,S004,Sneha,20,F,CSE,5.0,94,10,89,92,4,Pass,Excellent
15,S016,Simran,20,F,CSE,4.5,93,10,86,90,4,Pass,Excellent
7,S008,Neha,18,F,IT,4.5,91,9,82,88,4,Pass,Excellent
13,S014,Tanya,18,F,IT,4.0,89,9,78,84,4,Pass,Good
0,S001,Rahul,18,M,CSE,4.5,88,8,76,81,3,Pass,Good
5,S006,Anjali,19,F,ECE,4.0,85,9,74,79,3,Pass,Good
11,S012,Riya,19,F,ECE,3.0,82,8,71,75,3,Pass,Good
17,S018,Isha,19,F,ECE,3.5,81,8,70,73,3,Pass,Good
4,S005,Aman,18,M,IT,3.0,79,7,68,71,3,Pass,Good
8,S009,Vikash,19,M,ECE,3.5,77,7,65,69,2,Pass,Average
18,S019,Akash,20,M,CSE,3.0,76,7,64,67,3,Pass,Average
14,S015,Manish,19,M,ECE,2.5,74,6,59,63,2,Pass,Average
1,S002,Priya,19,F,CSE,2.0,72,6,61,58,2,Pass,Average
12,S013,Karan,20,M,CSE,2.0,70,5,52,48,2,Fail,Poor
6,S007,Rohit,20,M,CSE,2.5,68,5,55,51,2,Fail,Average
2,S003,Arjun,18,M,IT,1.5,65,4,48,42,1,Fail,Poor
16,S017,Dev,18,M,IT,1.5,63,4,46,40,1,Fail,Poor
9,S010,Pooja,20,F,CSE,1.0,61,3,44,38,1,Fail,Poor

In [ ]:
df.sort_values(
    ["Department", "Exam_Score"],
    ascending=[True, False]
)

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result,Performance
3,S004,Sneha,20,F,CSE,5.0,94,10,89,92,4,Pass,Excellent
15,S016,Simran,20,F,CSE,4.5,93,10,86,90,4,Pass,Excellent
0,S001,Rahul,18,M,CSE,4.5,88,8,76,81,3,Pass,Good
18,S019,Akash,20,M,CSE,3.0,76,7,64,67,3,Pass,Average
1,S002,Priya,19,F,CSE,2.0,72,6,61,58,2,Pass,Average
6,S007,Rohit,20,M,CSE,2.5,68,5,55,51,2,Fail,Average
12,S013,Karan,20,M,CSE,2.0,70,5,52,48,2,Fail,Poor
9,S010,Pooja,20,F,CSE,1.0,61,3,44,38,1,Fail,Poor
5,S006,Anjali,19,F,ECE,4.0,85,9,74,79,3,Pass,Good
11,S012,Riya,19,F,ECE,3.0,82,8,71,75,3,Pass,Good
17,S018,Isha,19,F,ECE,3.5,81,8,70,73,3,Pass,Good
8,S009,Vikash,19,M,ECE,3.5,77,7,65,69,2,Pass,Average
14,S015,Manish,19,M,ECE,2.5,74,6,59,63,2,Pass,Average
19,S020,Meera,18,F,IT,5.0,97,10,94,96,5,Pass,Excellent
10,S011,Aditya,18,M,IT,5.0,96,10,91,95,5,Pass,Excellent
7,S008,Neha,18,F,IT,4.5,91,9,82,88,4,Pass,Excellent
13,S014,Tanya,18,F,IT,4.0,89,9,78,84,4,Pass,Good
4,S005,Aman,18,M,IT,3.0,79,7,68,71,3,Pass,Good
2,S003,Arjun,18,M,IT,1.5,65,4,48,42,1,Fail,Poor
16,S017,Dev,18,M,IT,1.5,63,4,46,40,1,Fail,Poor

In [ ]:
df.sort_values(["Exam_Score"], ascending=[False]).head(3)

,Student_ID,Name,Age,Gender,Department,Study_Hours,Attendance,Assignments,Quiz_Score,Exam_Score,Projects,Result,Performance
19,S020,Meera,18,F,IT,5.0,97,10,94,96,5,Pass,Excellent
10,S011,Aditya,18,M,IT,5.0,96,10,91,95,5,Pass,Excellent
3,S004,Sneha,20,F,CSE,5.0,94,10,89,92,4,Pass,Excellent

In [ ]:
df.groupby("Department")["Study_Hours"].mean()

Department
CSE    3.0625
ECE    3.3000
IT     3.5000
Name: Study_Hours, dtype: float64

In [ ]:
df.groupby("Department")["Exam_Score"].max()

Department
CSE    92
ECE    79
IT     96
Name: Exam_Score, dtype: int64

In [ ]:
df.groupby("Department")["Quiz_Score"].mean()

Department
CSE    65.875000
ECE    67.800000
IT     72.428571
Name: Quiz_Score, dtype: float64

In [ ]:
df.groupby("Department").size()

Department
CSE    8
ECE    5
IT     7
dtype: int64

In [ ]:
print("Avrage Exam Score for CSE is: ",df[df["Department"] == "CSE"]["Exam_Score"].mean())

Avrage Exam Score for CSE is:  65.625

In [ ]:
df["Total_Score"] = df["Exam_Score"] + df["Quiz_Score"]
print(df)

   Student_ID    Name  Age Gender Department  Study_Hours  Attendance  \
0        S001   Rahul   18      M        CSE          4.5          88
1        S002   Priya   19      F        CSE          2.0          72
2        S003   Arjun   18      M         IT          1.5          65
3        S004   Sneha   20      F        CSE          5.0          94
4        S005    Aman   18      M         IT          3.0          79
5        S006  Anjali   19      F        ECE          4.0          85
6        S007   Rohit   20      M        CSE          2.5          68
7        S008    Neha   18      F         IT          4.5          91
8        S009  Vikash   19      M        ECE          3.5          77
9        S010   Pooja   20      F        CSE          1.0          61
10       S011  Aditya   18      M         IT          5.0          96
11       S012    Riya   19      F        ECE          3.0          82
12       S013   Karan   20      M        CSE          2.0          70
13       S014   Tanya   18      F         IT          4.0          89
14       S015  Manish   19      M        ECE          2.5          74
15       S016  Simran   20      F        CSE          4.5          93
16       S017     Dev   18      M         IT          1.5          63
17       S018    Isha   19      F        ECE          3.5          81
18       S019   Akash   20      M        CSE          3.0          76
19       S020   Meera   18      F         IT          5.0          97

    Assignments  Quiz_Score  Exam_Score  Projects Result Performance  \
0             8          76          81         3   Pass        Good
1             6          61          58         2   Pass     Average
2             4          48          42         1   Fail        Poor
3            10          89          92         4   Pass   Excellent
4             7          68          71         3   Pass        Good
5             9          74          79         3   Pass        Good
6             5          55          51         2   Fail     Average
7             9          82          88         4   Pass   Excellent
8             7          65          69         2   Pass     Average
9             3          44          38         1   Fail        Poor
10           10          91          95         5   Pass   Excellent
11            8          71          75         3   Pass        Good
12            5          52          48         2   Fail        Poor
13            9          78          84         4   Pass        Good
14            6          59          63         2   Pass     Average
15           10          86          90         4   Pass   Excellent
16            4          46          40         1   Fail        Poor
17            8          70          73         3   Pass        Good
18            7          64          67         3   Pass     Average
19           10          94          96         5   Pass   Excellent

    Total_Score
0           157
1           119
2            90
3           181
4           139
5           153
6           106
7           170
8           134
9            82
10          186
11          146
12          100
13          162
14          122
15          176
16           86
17          143
18          131
19          190

In [ ]:
def Study_Level(Study_hours):
  if Study_hours >= 4:
    return "High"
  elif Study_hours >=2:
    return "Medium"
  else:
    return "Low"


df["Study_Level"] = df["Study_Hours"].apply(Study_Level)
print(df)

   Student_ID    Name  Age Gender Department  Study_Hours  Attendance  \
0        S001   Rahul   18      M        CSE          4.5          88
1        S002   Priya   19      F        CSE          2.0          72
2        S003   Arjun   18      M         IT          1.5          65
3        S004   Sneha   20      F        CSE          5.0          94
4        S005    Aman   18      M         IT          3.0          79
5        S006  Anjali   19      F        ECE          4.0          85
6        S007   Rohit   20      M        CSE          2.5          68
7        S008    Neha   18      F         IT          4.5          91
8        S009  Vikash   19      M        ECE          3.5          77
9        S010   Pooja   20      F        CSE          1.0          61
10       S011  Aditya   18      M         IT          5.0          96
11       S012    Riya   19      F        ECE          3.0          82
12       S013   Karan   20      M        CSE          2.0          70
13       S014   Tanya   18      F         IT          4.0          89
14       S015  Manish   19      M        ECE          2.5          74
15       S016  Simran   20      F        CSE          4.5          93
16       S017     Dev   18      M         IT          1.5          63
17       S018    Isha   19      F        ECE          3.5          81
18       S019   Akash   20      M        CSE          3.0          76
19       S020   Meera   18      F         IT          5.0          97

    Assignments  Quiz_Score  Exam_Score  Projects Result Performance  \
0             8          76          81         3   Pass        Good
1             6          61          58         2   Pass     Average
2             4          48          42         1   Fail        Poor
3            10          89          92         4   Pass   Excellent
4             7          68          71         3   Pass        Good
5             9          74          79         3   Pass        Good
6             5          55          51         2   Fail     Average
7             9          82          88         4   Pass   Excellent
8             7          65          69         2   Pass     Average
9             3          44          38         1   Fail        Poor
10           10          91          95         5   Pass   Excellent
11            8          71          75         3   Pass        Good
12            5          52          48         2   Fail        Poor
13            9          78          84         4   Pass        Good
14            6          59          63         2   Pass     Average
15           10          86          90         4   Pass   Excellent
16            4          46          40         1   Fail        Poor
17            8          70          73         3   Pass        Good
18            7          64          67         3   Pass     Average
19           10          94          96         5   Pass   Excellent

    Total_Score Study_Level
0           157        High
1           119      Medium
2            90         Low
3           181        High
4           139      Medium
5           153        High
6           106      Medium
7           170        High
8           134      Medium
9            82         Low
10          186        High
11          146      Medium
12          100      Medium
13          162        High
14          122      Medium
15          176        High
16           86         Low
17          143      Medium
18          131      Medium
19          190        High

In [ ]:
def Attendance_status(Attendance):
  if Attendance >=85:
    return "Good"
  elif Attendance >=70:
    return "Average"
  else:
    return "Poor"

df["Attendance_Status"] = df["Attendance"].apply(Attendance_status)
print(df)

   Student_ID    Name  Age Gender Department  Study_Hours  Attendance  \
0        S001   Rahul   18      M        CSE          4.5          88
1        S002   Priya   19      F        CSE          2.0          72
2        S003   Arjun   18      M         IT          1.5          65
3        S004   Sneha   20      F        CSE          5.0          94
4        S005    Aman   18      M         IT          3.0          79
5        S006  Anjali   19      F        ECE          4.0          85
6        S007   Rohit   20      M        CSE          2.5          68
7        S008    Neha   18      F         IT          4.5          91
8        S009  Vikash   19      M        ECE          3.5          77
9        S010   Pooja   20      F        CSE          1.0          61
10       S011  Aditya   18      M         IT          5.0          96
11       S012    Riya   19      F        ECE          3.0          82
12       S013   Karan   20      M        CSE          2.0          70
13       S014   Tanya   18      F         IT          4.0          89
14       S015  Manish   19      M        ECE          2.5          74
15       S016  Simran   20      F        CSE          4.5          93
16       S017     Dev   18      M         IT          1.5          63
17       S018    Isha   19      F        ECE          3.5          81
18       S019   Akash   20      M        CSE          3.0          76
19       S020   Meera   18      F         IT          5.0          97

    Assignments  Quiz_Score  Exam_Score  Projects Result Performance  \
0             8          76          81         3   Pass        Good
1             6          61          58         2   Pass     Average
2             4          48          42         1   Fail        Poor
3            10          89          92         4   Pass   Excellent
4             7          68          71         3   Pass        Good
5             9          74          79         3   Pass        Good
6             5          55          51         2   Fail     Average
7             9          82          88         4   Pass   Excellent
8             7          65          69         2   Pass     Average
9             3          44          38         1   Fail        Poor
10           10          91          95         5   Pass   Excellent
11            8          71          75         3   Pass        Good
12            5          52          48         2   Fail        Poor
13            9          78          84         4   Pass        Good
14            6          59          63         2   Pass     Average
15           10          86          90         4   Pass   Excellent
16            4          46          40         1   Fail        Poor
17            8          70          73         3   Pass        Good
18            7          64          67         3   Pass     Average
19           10          94          96         5   Pass   Excellent

    Total_Score Study_Level Attendance_Status
0           157        High              Good
1           119      Medium           Average
2            90         Low              Poor
3           181        High              Good
4           139      Medium           Average
5           153        High              Good
6           106      Medium              Poor
7           170        High              Good
8           134      Medium           Average
9            82         Low              Poor
10          186        High              Good
11          146      Medium           Average
12          100      Medium           Average
13          162        High              Good
14          122      Medium           Average
15          176        High              Good
16           86         Low              Poor
17          143      Medium           Average
18          131      Medium           Average
19          190        High              Good

In [ ]:
df.loc[df["Exam_Score"].idxmax(), "Name"]

'Meera'

In [ ]:
df.loc[df["Attendance"].idxmin(), "Name"]

'Pooja'

In [ ]:
df.loc[df["Study_Hours"].idxmax(), "Name"]

'Sneha'

In [ ]:
df.groupby("Gender").size()

Gender
F    10
M    10
dtype: int64

In [ ]:
df["Department"].value_counts(normalize=True) * 100

Department
CSE    40.0
IT     35.0
ECE    25.0
Name: proportion, dtype: float64

In [ ]:
df["Result"].value_counts(normalize=True)*100

Result
Pass    75.0
Fail    25.0
Name: proportion, dtype: float64

In [ ]:
df["Study_Hours"].corr(df["Exam_Score"])

np.float64(0.9730247012728716)

In [ ]:
df["Attendance"].corr(df["Exam_Score"])

np.float64(0.9916767585395001)

In [ ]:
df["Quiz_Score"].corr(df["Exam_Score"])

np.float64(0.9892842387727674)

In [ ]:
df.groupby("Department")["Exam_Score"].mean().idxmax()

'IT'

In [ ]:
df.loc[df["Exam_Score"].idxmax(), "Name" ]

'Meera'

In [ ]:
(df["Result"] == "Pass").mean() * 100

np.float64(75.0)

In [ ]:
df.loc[df['Attendance'].idxmax(), "Name"]

'Meera'

In [ ]:
df[df["Study_Hours"] > 4]["Exam_Score"].mean()

np.float64(90.33333333333333)

In [ ]:
df[df["Attendance"] > 85]["Exam_Score"].mean()

np.float64(89.42857142857143)

In [ ]:
df["Department"].value_counts().idxmax()

'CSE'

In [ ]:
df["Study_Hours"].corr(df["Exam_Score"])

np.float64(0.9730247012728716)

In [ ]:
student_counts = df["Student_ID"].count()

In [ ]:
print("STUDENT PERFORMANCE REPORT")
print("Total Students: ",student_counts)
print("Average Exam Score: ",df["Exam_Score"].mean())
print("Highest Exam Score: ",df["Exam_Score"].idxmax())
print("Lowest Exam Score: ",df["Exam_Score"].idxmin())
print("Best Performing Departmeant: ", df.groupby("Department")["Exam_Score"].mean().idxmax())
print("Most Studenst Department: ",df["Department"].value_counts().idxmax())
print("Average Study Hours: ", df["Study_Hours"].mean())
print("Average Attendance: ", df["Attendance"].mean())
print("Highest Exam Score: ", df["Exam_Score"].max())
print("Lowest Exam Score: ", df["Exam_Score"].min())

STUDENT PERFORMANCE REPORT
Total Students:  20
Average Exam Score:  70.0
Highest Exam Score:  19
Lowest Exam Score:  9
Best Performing Departmeant:  IT
Most Studenst Department:  CSE
Average Study Hours:  3.275
Average Attendance:  80.05
Highest Exam Score:  96
Lowest Exam Score:  38